# Site settings
title: Solace Samples SEMP
baseurl: "/solace-samples-semp" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-semp

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links to docs. Using variables to make it easy to keep up to date
docs-overview: http://docs.solacesystems.com/concepts/overview
docs-concepts-paging: http://docs.solacesystems.com/concepts/paging
docs-concepts-uri: http://docs.solacesystems.com/concepts/uri
docs-api: http://docs.solacesystems.com
dosc-schema: http://docs.solacesystem.com/awesomeschema


#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
